# @package _global_

defaults:
  - base_torch

model:
  _target_: darts.models.forecasting.rnn_model.RNNModel
  input_chunk_length: 53
  hidden_dim: 50
  model: LSTM
  n_rnn_layers: 1
  dropout: 0.2
  training_length: ${eval:'${eval.kwargs.forecast_horizon} + ${model.input_chunk_length}'}
  loss_fn:
    _target_: torch.nn.MSELoss
  optimizer_kwargs:
    lr: 1.830791720900803e-05

datamodule:
  data_variables:
    future_covariates:
      - "filterpressure_1"
      - "methanol"
      - "nitrate_in"
      - "tunnelwater"

lr_tuner: null
