# @package _global_

defaults:
  - elastic_net

model:
  lags: 273
  output_chunk_length: 1
  multi_models: False
  model:
    l1_ratio: 0.4229215348040755
  lags_future_covariates:
    _target_: builtins.tuple
    _args_:
      - - ${model.lags}
        - 0

datamodule:
  data_variables:
    future_covariates:
      - "ammonium"
      - "filterpressure_8"
      - "methanol"
      - "nitrate_in"
      - "oxygen"
      - "temp"
